---
name: Business-DK-CPR
version: 0.03
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
abstract: a danish CPR code generator/validator
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Business::DK::CVR: 0.01
  Business::DK::PO: 0.02
  Carp: 0
  Date::Calc: 0
  Exporter: 0
  Test::Exception: 0
provides:
  Business::DK::CPR:
    file: lib/Business/DK/CPR.pm
    version: 0.03
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
