---
abstract: 'Danish CPR code generator/validator'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Prereq::Build: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-DK-CPR
provides:
  Business::DK::CPR:
    file: lib/Business/DK/CPR.pm
    version: '0.11'
  Class::Business::DK::CPR:
    file: lib/Class/Business/DK/CPR.pm
    version: '0.11'
  Data::FormValidator::Constraints::Business::DK::CPR:
    file: lib/Data/FormValidator/Constraints/Business/DK/CPR.pm
    version: '0.11'
requires:
  Business::DK::CVR: '0.01'
  Carp: '0'
  Class::InsideOut: '0'
  Date::Calc: '0'
  Exporter: '0'
  Params::Validate: '0'
  Readonly: '0'
  Tie::IxHash: '0'
  perl: v5.10.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-CPR
  homepage: http://logiclab.jira.com/wiki/display/BDKCPR/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  projectChangelog: http://logiclab.jira.com/browse/BDKCPR#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/BDKCPR
  projectWiki: http://logiclab.jira.com/wiki/display/BDKCPR/Home
  repository: https://github.com/jonasbn/bdkcpr
version: '0.11'
