---
abstract: 'Danish CPR code generator/validator'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Prereq::Build: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-DK-CPR
provides:
  Business::DK::CPR:
    file: lib/Business/DK/CPR.pm
    version: 0.07
  Class::Business::DK::CPR:
    file: lib/Class/Business/DK/CPR.pm
    version: 0.01
  Data::FormValidator::Constraints::Business::DK::CPR:
    file: lib/Data/FormValidator/Constraints/Business/DK/CPR.pm
    version: 0.01
requires:
  Business::DK::CVR: 0.01
  Carp: 0
  Class::InsideOut: 0
  Date::Calc: 0
  Exporter: 0
  Readonly: 0
  Tie::IxHash: 0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/BDKCPR#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/BDKCPR
  ProjectWiki: http://logiclab.jira.com/wiki/display/BDKCPR/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-CPR
  homepage: http://logiclab.jira.com/wiki/display/BDKCPR/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/BDKCPR
version: 0.07
